In [2]:
import pandas as pd
import os

In [10]:
caminho = r"F:\Ponto Data\Reportagens\Cinema Ponta Grossa\Bilheteria diária"

In [4]:
arquivos = [f for f in os.listdir(caminho) if f.endswith('.csv')]
print("Arquivos encontrados:", arquivos)

Arquivos encontrados: ['bilheteria-diaria-obras-por-exibidoras-2014-06-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2014-06-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2014-06-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2014-06-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2014-06-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2014-07-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2014-07-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2015-05-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2015-05-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2015-05-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2015-05-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2015-06-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2015-06-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2015-06-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2015-06-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2015-06-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2015-07-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2015-07-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2015-12-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2015-12-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2015-12-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-01-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-01-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-01-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-01-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-01-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-02-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-02-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-02-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-02-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-02-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-03-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-03-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-03-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-03-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-03-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-04-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-04-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-04-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-04-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-04-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-05-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-05-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-05-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-05-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-05-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-06-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-06-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-06-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-06-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-06-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-07-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-07-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-07-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-07-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-07-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-08-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-08-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-08-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-08-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-08-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-09-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-09-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-09-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-09-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-09-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-10-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-10-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-10-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-10-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-10-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-11-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-11-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-11-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-11-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-11-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-12-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-12-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-12-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-12-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2016-12-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-01-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-01-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-01-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-01-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-01-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-02-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-02-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-02-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-02-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-03-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-03-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-03-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-03-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-03-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-04-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-04-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-04-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-04-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-04-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-05-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-05-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-05-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-05-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-05-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-06-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-06-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-06-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-06-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-06-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-07-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-07-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-07-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-07-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-07-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-08-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-08-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-08-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-08-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-08-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-09-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-09-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-09-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-09-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-09-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-10-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-10-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-10-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-10-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-10-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-11-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-11-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-11-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-11-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-11-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-12-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-12-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-12-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-12-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2017-12-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-01-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-01-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-01-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-01-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-01-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-02-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-02-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-02-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-02-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-03-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-03-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-03-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-03-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-03-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-04-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-04-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-04-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-04-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-04-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-05-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-05-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-05-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-05-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-05-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-06-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-06-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-06-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-06-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-06-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-07-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-07-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-07-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-07-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-07-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-08-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-08-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-08-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-08-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-08-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-09-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-09-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-09-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-09-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-09-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-10-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-10-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-10-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-10-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-10-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-11-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-11-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-11-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-11-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-11-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-12-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-12-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-12-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-12-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2018-12-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-01-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-01-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-01-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-01-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-01-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-02-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-02-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-02-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-02-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-03-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-03-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-03-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-03-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-03-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-04-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-04-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-04-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-04-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-04-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-05-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-05-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-05-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-05-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-05-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-06-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-06-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-06-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-06-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-06-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-07-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-07-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-07-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-07-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-07-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-08-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-08-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-08-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-08-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-08-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-09-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-09-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-09-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-09-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-09-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-10-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-10-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-10-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-10-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-10-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-11-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-11-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-11-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-11-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-11-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-12-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-12-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-12-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-12-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2019-12-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-01-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-01-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-01-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-01-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-01-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-02-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-02-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-02-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-02-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-02-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-03-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-03-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-03-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-03-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-03-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-04-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-04-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-04-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-04-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-05-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-05-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-05-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-05-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-05-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-06-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-06-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-06-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-06-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-06-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-07-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-07-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-07-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-07-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-07-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-08-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-08-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-08-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-08-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-08-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-09-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-09-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-09-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-09-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-09-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-10-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-10-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-10-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-10-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-10-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-11-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-11-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-11-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-11-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-11-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-12-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-12-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-12-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-12-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2020-12-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2021-01-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2021-01-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2021-01-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2021-01-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2021-01-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2021-02-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2021-02-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2021-02-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2021-02-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2021-03-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2021-03-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2021-03-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2021-03-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2021-03-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2021-04-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2021-04-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2021-04-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2021-04-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2021-04-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2021-05-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2021-05-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2021-05-s03.csv', 'bilheteria-diaria-obras-por-exibidoras-2021-05-s04.csv', 'bilheteria-diaria-obras-por-exibidoras-2021-05-s05.csv', 'bilheteria-diaria-obras-por-exibidoras-2021-06-s01.csv', 'bilheteria-diaria-obras-por-exibidoras-2021-06-s02.csv', 'bilheteria-diaria-obras-por-exibidoras-2021-06-s03.csv', 'bilheteria-diaria-obras-

In [5]:
for arquivo in arquivos:
    caminho_arquivo = os.path.join(caminho, arquivo)
    print(f"Lendo: {arquivo}")

Lendo: bilheteria-diaria-obras-por-exibidoras-2014-06-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2014-06-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2014-06-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2014-06-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2014-06-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2014-07-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2014-07-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2015-05-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2015-05-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2015-05-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2015-05-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2015-06-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2015-06-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2015-06-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2015-06-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2015-06-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2015-07-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2015-07-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2015-12-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2015-12-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2015-12-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-01-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-01-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-01-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-01-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-01-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-02-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-02-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-02-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-02-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-02-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-03-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-03-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-03-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-03-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-03-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-04-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-04-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-04-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-04-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-04-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-05-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-05-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-05-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-05-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-05-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-06-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-06-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-06-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-06-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-06-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-07-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-07-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-07-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-07-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-07-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-08-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-08-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-08-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-08-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-08-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-09-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-09-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-09-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-09-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-09-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-10-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-10-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-10-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-10-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-10-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-11-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-11-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-11-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-11-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-11-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-12-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-12-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-12-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-12-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-12-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-01-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-01-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-01-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-01-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-01-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-02-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-02-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-02-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-02-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-03-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-03-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-03-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-03-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-03-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-04-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-04-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-04-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-04-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-04-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-05-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-05-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-05-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-05-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-05-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-06-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-06-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-06-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-06-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-06-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-07-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-07-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-07-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-07-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-07-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-08-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-08-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-08-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-08-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-08-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-09-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-09-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-09-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-09-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-09-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-10-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-10-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-10-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-10-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-10-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-11-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-11-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-11-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-11-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-11-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-12-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-12-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-12-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-12-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-12-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-01-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-01-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-01-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-01-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-01-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-02-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-02-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-02-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-02-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-03-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-03-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-03-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-03-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-03-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-04-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-04-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-04-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-04-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-04-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-05-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-05-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-05-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-05-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-05-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-06-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-06-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-06-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-06-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-06-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-07-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-07-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-07-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-07-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-07-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-08-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-08-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-08-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-08-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-08-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-09-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-09-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-09-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-09-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-09-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-10-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-10-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-10-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-10-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-10-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-11-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-11-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-11-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-11-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-11-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-12-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-12-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-12-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-12-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-12-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-01-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-01-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-01-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-01-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-01-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-02-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-02-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-02-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-02-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-03-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-03-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-03-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-03-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-03-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-04-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-04-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-04-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-04-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-04-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-05-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-05-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-05-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-05-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-05-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-06-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-06-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-06-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-06-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-06-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-07-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-07-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-07-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-07-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-07-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-08-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-08-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-08-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-08-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-08-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-09-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-09-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-09-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-09-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-09-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-10-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-10-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-10-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-10-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-10-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-11-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-11-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-11-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-11-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-11-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-12-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-12-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-12-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-12-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-12-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-01-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-01-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-01-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-01-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-01-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-02-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-02-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-02-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-02-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-02-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-03-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-03-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-03-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-03-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-03-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-04-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-04-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-04-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-04-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-05-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-05-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-05-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-05-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-05-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-06-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-06-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-06-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-06-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-06-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-07-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-07-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-07-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-07-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-07-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-08-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-08-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-08-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-08-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-08-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-09-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-09-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-09-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-09-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-09-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-10-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-10-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-10-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-10-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-10-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-11-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-11-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-11-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-11-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-11-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-12-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-12-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-12-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-12-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-12-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2021-01-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2021-01-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2021-01-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2021-01-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2021-01-s05.csv

In [6]:
df = pd.read_csv(caminho_arquivo, sep=None, engine='python')

In [7]:
df.head()

,DATA_EXIBICAO,SESSAO,TITULO_ORIGINAL,TITULO_BRASIL,CPB_ROE,AUDIO,LEGENDADA,PAIS_OBRA,REGISTRO_SALA,NOME_SALA,PUBLICO,REGISTRO_GRUPO_EXIBIDOR,REGISTRO_EXIBIDOR,REGISTRO_COMPLEXO,MUNICIPIO_SALA_COMPLEXO,UF_SALA_COMPLEXO,RAZAO_SOCIAL_EXIBIDORA,CNPJ_EXIBIDORA
0,08/10/2025,08/10/2025 08:00:00,ABÁ E SUA BANDA,NaN,B2400235800000,ORIGINAL,NÃO,BRASIL,5007329,CINE SÃO PEDRO DA ALDEIA 01,47,NaN,18872,62433,SÃO PEDRO DA ALDEIA,RJ,CINE TEATRO SHOPPING SÃO PEDRO LTDA-ME,04.180.876/0001-18
1,08/10/2025,08/10/2025 08:00:00,ABÁ E SUA BANDA,NaN,B2400235800000,ORIGINAL,NÃO,BRASIL,5007330,CINE SÃO PEDRO DA ALDEIA 02,49,NaN,18872,62433,SÃO PEDRO DA ALDEIA,RJ,CINE TEATRO SHOPPING SÃO PEDRO LTDA-ME,04.180.876/0001-18
2,08/10/2025,08/10/2025 08:00:00,ELIO,ELIO,E2500204800000,DUBLADO,NÃO,ESTADOS UNIDOS,5006502,CINEPOLIS TRES LAGOAS 02,100,6000024.0,17266,44843,TRÊS LAGOAS,MS,CINEPOLIS OPERADORA DE CINEMAS DO BRASIL LTDA,09.652.820/0001-32
3,08/10/2025,08/10/2025 08:00:00,GEUGJANGPAN SYUPEO WINGSEU: MAEGSIMEOM SEUPIDEU,SUPER WINGS EM VELOCIDADE MÁXIMA,E2500131700000,DUBLADO,NÃO,CHINA,5006309,MOVIECOM VALE DO AÇO SALA 05,42,6000100.0,2923,2924,IPATINGA,MG,EMPRESA CINEMATOGRÁFICA IPATINGA LTDA,02.962.893/0001-81
4,08/10/2025,08/10/2025 08:00:00,LILO & STITCH,LILO & STITCH,E2500174800000,DUBLADO,NÃO,ESTADOS UNIDOS,5001489,MOVIECOM PRUDENSHOPPING 3,40,6000100.0,2914,2915,PRESIDENTE PRUDENTE,SP,CINEMATOGRÁFICA PASSOS LTDA,01.688.909/0001-47

In [13]:
lista_df = []

for arquivo in arquivos:
    caminho_arquivo = os.path.join(caminho, arquivo)
    print("Lendo:", arquivo)
    
    df = pd.read_csv(caminho_arquivo, sep=None, engine='python')
    
    lista_df.append(df)

df_final = pd.concat(lista_df, ignore_index=True)

Lendo: bilheteria-diaria-obras-por-exibidoras-2014-06-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2014-06-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2014-06-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2014-06-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2014-06-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2014-07-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2014-07-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2015-05-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2015-05-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2015-05-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2015-05-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2015-06-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2015-06-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2015-06-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2015-06-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2015-06-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2015-07-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2015-07-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2015-12-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2015-12-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2015-12-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-01-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-01-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-01-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-01-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-01-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-02-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-02-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-02-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-02-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-02-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-03-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-03-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-03-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-03-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-03-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-04-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-04-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-04-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-04-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-04-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-05-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-05-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-05-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-05-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-05-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-06-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-06-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-06-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-06-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-06-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-07-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-07-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-07-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-07-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-07-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-08-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-08-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-08-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-08-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-08-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-09-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-09-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-09-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-09-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-09-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-10-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-10-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-10-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-10-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-10-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-11-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-11-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-11-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-11-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-11-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-12-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-12-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-12-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-12-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2016-12-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-01-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-01-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-01-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-01-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-01-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-02-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-02-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-02-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-02-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-03-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-03-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-03-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-03-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-03-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-04-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-04-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-04-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-04-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-04-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-05-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-05-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-05-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-05-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-05-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-06-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-06-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-06-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-06-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-06-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-07-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-07-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-07-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-07-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-07-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-08-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-08-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-08-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-08-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-08-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-09-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-09-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-09-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-09-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-09-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-10-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-10-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-10-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-10-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-10-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-11-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-11-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-11-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-11-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-11-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-12-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-12-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-12-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-12-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2017-12-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-01-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-01-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-01-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-01-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-01-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-02-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-02-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-02-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-02-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-03-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-03-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-03-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-03-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-03-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-04-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-04-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-04-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-04-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-04-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-05-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-05-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-05-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-05-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-05-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-06-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-06-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-06-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-06-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-06-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-07-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-07-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-07-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-07-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-07-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-08-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-08-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-08-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-08-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-08-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-09-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-09-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-09-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-09-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-09-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-10-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-10-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-10-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-10-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-10-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-11-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-11-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-11-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-11-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-11-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-12-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-12-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-12-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-12-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2018-12-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-01-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-01-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-01-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-01-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-01-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-02-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-02-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-02-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-02-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-03-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-03-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-03-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-03-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-03-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-04-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-04-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-04-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-04-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-04-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-05-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-05-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-05-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-05-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-05-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-06-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-06-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-06-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-06-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-06-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-07-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-07-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-07-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-07-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-07-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-08-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-08-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-08-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-08-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-08-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-09-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-09-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-09-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-09-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-09-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-10-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-10-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-10-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-10-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-10-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-11-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-11-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-11-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-11-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-11-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-12-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-12-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-12-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-12-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2019-12-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-01-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-01-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-01-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-01-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-01-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-02-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-02-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-02-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-02-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-02-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-03-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-03-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-03-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-03-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-03-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-04-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-04-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-04-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-04-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-05-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-05-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-05-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-05-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-05-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-06-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-06-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-06-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-06-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-06-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-07-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-07-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-07-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-07-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-07-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-08-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-08-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-08-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-08-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-08-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-09-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-09-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-09-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-09-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-09-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-10-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-10-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-10-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-10-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-10-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-11-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-11-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-11-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-11-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-11-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-12-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-12-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-12-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-12-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2020-12-s05.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2021-01-s01.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2021-01-s02.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2021-01-s03.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2021-01-s04.csv
Lendo: bilheteria-diaria-obras-por-exibidoras-2021-01-s05.csv

In [15]:
df_final.head()

,DATA_EXIBICAO,SESSAO,TITULO_ORIGINAL,TITULO_BRASIL,CPB_ROE,AUDIO,LEGENDADA,PAIS_OBRA,REGISTRO_SALA,NOME_SALA,PUBLICO,REGISTRO_GRUPO_EXIBIDOR,REGISTRO_EXIBIDOR,REGISTRO_COMPLEXO,MUNICIPIO_SALA_COMPLEXO,UF_SALA_COMPLEXO,RAZAO_SOCIAL_EXIBIDORA,CNPJ_EXIBIDORA
0,01/06/2014,01/06/2014 14:00:00,NOAH,NOÉ,E1402510400000,ORIGINAL,SIM,ESTADOS UNIDOS,5004483,ARAPIRACA BRA 01,0,6000027.0,22546,26037,ARAPIRACA,AL,REDECINE BRA CINEMATOGRÁFICA S.A.,15.422.993/0001-67
1,01/06/2014,01/06/2014 17:00:00,NOAH,NOÉ,E1402510400000,ORIGINAL,SIM,ESTADOS UNIDOS,5004483,ARAPIRACA BRA 01,0,6000027.0,22546,26037,ARAPIRACA,AL,REDECINE BRA CINEMATOGRÁFICA S.A.,15.422.993/0001-67
2,01/06/2014,01/06/2014 19:00:00,NOAH,NOÉ,E1402510400000,ORIGINAL,SIM,ESTADOS UNIDOS,5004483,ARAPIRACA BRA 01,0,6000027.0,22546,26037,ARAPIRACA,AL,REDECINE BRA CINEMATOGRÁFICA S.A.,15.422.993/0001-67
3,01/06/2014,01/06/2014 22:00:00,NOAH,NOÉ,E1402510400000,ORIGINAL,SIM,ESTADOS UNIDOS,5004483,ARAPIRACA BRA 01,0,6000027.0,22546,26037,ARAPIRACA,AL,REDECINE BRA CINEMATOGRÁFICA S.A.,15.422.993/0001-67
4,11/06/2014,11/06/2014 13:00:00,DIVERGENT,DIVERGENTE,E1402640000000,ORIGINAL,SIM,ESTADOS UNIDOS,5004484,ARAPIRACA BRA 02,0,6000027.0,22546,26037,ARAPIRACA,AL,REDECINE BRA CINEMATOGRÁFICA S.A.,15.422.993/0001-67

In [16]:
df_final['PUBLICO'].value_counts().head(20)

PUBLICO
0     1919643
2     1460173
4     1259505
6     1103506
5     1039027
3     1025646
8      985366
7      963066
9      877461
10     872510
11     810402
12     790863
13     721200
14     695539
15     653582
1      627352
16     618756
17     583554
18     559327
19     526091
Name: count, dtype: int64

In [23]:
saida = os.path.join(caminho, "bilheteria_brasil.csv")
df_final.to_csv(saida, index=False, encoding='utf-8-sig')

print("✅ Arquivo salvo em:", saida)

✅ Arquivo salvo em: F:\Ponto Data\Reportagens\Cinema Ponta Grossa\Bilheteria diária\bilheteria_brasil.csv

# Arquivo concatenado com todo o histórico da Ancine

In [7]:
bilheteria_brasil = r"F:\Ponto Data\Reportagens\Cinema Ponta Grossa\Bilheteria diária\bilheteria_brasil.csv"


df_bilheteria = pd.read_csv(bilheteria_brasil, sep=',', encoding='utf-8')
df_bilheteria.head()

,DATA_EXIBICAO,SESSAO,TITULO_ORIGINAL,TITULO_BRASIL,CPB_ROE,AUDIO,LEGENDADA,PAIS_OBRA,REGISTRO_SALA,NOME_SALA,PUBLICO,REGISTRO_GRUPO_EXIBIDOR,REGISTRO_EXIBIDOR,REGISTRO_COMPLEXO,MUNICIPIO_SALA_COMPLEXO,UF_SALA_COMPLEXO,RAZAO_SOCIAL_EXIBIDORA,CNPJ_EXIBIDORA
0,01/06/2014,01/06/2014 14:00:00,NOAH,NOÉ,E1402510400000,ORIGINAL,SIM,ESTADOS UNIDOS,5004483,ARAPIRACA BRA 01,0,6000027.0,22546,26037,ARAPIRACA,AL,REDECINE BRA CINEMATOGRÁFICA S.A.,15.422.993/0001-67
1,01/06/2014,01/06/2014 17:00:00,NOAH,NOÉ,E1402510400000,ORIGINAL,SIM,ESTADOS UNIDOS,5004483,ARAPIRACA BRA 01,0,6000027.0,22546,26037,ARAPIRACA,AL,REDECINE BRA CINEMATOGRÁFICA S.A.,15.422.993/0001-67
2,01/06/2014,01/06/2014 19:00:00,NOAH,NOÉ,E1402510400000,ORIGINAL,SIM,ESTADOS UNIDOS,5004483,ARAPIRACA BRA 01,0,6000027.0,22546,26037,ARAPIRACA,AL,REDECINE BRA CINEMATOGRÁFICA S.A.,15.422.993/0001-67
3,01/06/2014,01/06/2014 22:00:00,NOAH,NOÉ,E1402510400000,ORIGINAL,SIM,ESTADOS UNIDOS,5004483,ARAPIRACA BRA 01,0,6000027.0,22546,26037,ARAPIRACA,AL,REDECINE BRA CINEMATOGRÁFICA S.A.,15.422.993/0001-67
4,11/06/2014,11/06/2014 13:00:00,DIVERGENT,DIVERGENTE,E1402640000000,ORIGINAL,SIM,ESTADOS UNIDOS,5004484,ARAPIRACA BRA 02,0,6000027.0,22546,26037,ARAPIRACA,AL,REDECINE BRA CINEMATOGRÁFICA S.A.,15.422.993/0001-67

In [12]:
total_linhas = len(df_bilheteria)
print(f"O DataFrame tem {total_linhas} linhas.")
df_bilheteria.info()

O DataFrame tem 33810797 linhas.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33810797 entries, 0 to 33810796
Data columns (total 18 columns):
 #   Column                   Dtype
---  ------                   -----
 0   DATA_EXIBICAO            object
 1   SESSAO                   object
 2   TITULO_ORIGINAL          object
 3   TITULO_BRASIL            object
 4   CPB_ROE                  object
 5   AUDIO                    object
 6   LEGENDADA                object
 7   PAIS_OBRA                object
 8   REGISTRO_SALA            int64
 9   NOME_SALA                object
 10  PUBLICO                  int64
 11  REGISTRO_GRUPO_EXIBIDOR  float64
 12  REGISTRO_EXIBIDOR        int64
 13  REGISTRO_COMPLEXO        int64
 14  MUNICIPIO_SALA_COMPLEXO  object
 15  UF_SALA_COMPLEXO         object
 16  RAZAO_SOCIAL_EXIBIDORA   object
 17  CNPJ_EXIBIDORA           object
dtypes: float64(1), int64(4), object(13)
memory usage: 4.5+ GB

In [13]:
df_bilheteria['PUBLICO'].value_counts().head(20)

PUBLICO
0     1919643
2     1460173
4     1259505
6     1103506
5     1039027
3     1025646
8      985366
7      963066
9      877461
10     872510
11     810402
12     790863
13     721200
14     695539
15     653582
1      627352
16     618756
17     583554
18     559327
19     526091
Name: count, dtype: int64

In [16]:
df_zero_brasil = df_bilheteria[df_bilheteria["PUBLICO"] == 0]
contagem_filmes = df_zero_brasil["TITULO_BRASIL"].value_counts().head(10)
print("Top 10 filmes que aparecem com público zero:")
print(contagem_filmes)

Top 10 filmes que aparecem com público zero:
TITULO_BRASIL
MULHER-MARAVILHA 1984          12198
TOM & JERRY - O FILME          10496
SUPER MARIO BROS. - O FILME     8811
MINIONS 2: A ORIGEM DE GRU      7931
TROLLS 3 - JUNTOS NOVAMENTE     7863
UM FILME MINECRAFT              7606
LILO & STITCH                   7291
LIGHTYEAR                       6879
TROLLS 2                        6792
MUNDO ESTRANHO                  6749
Name: count, dtype: int64